# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Preview Image To Docker Hub

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: Build a preview container image and push to Docker Hub 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        description: 
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        description: Outputs available platforms from BuildX
        run: echo ${{ steps.buildx.outputs.platforms }}
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:docker/ubuntu"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ansible-azure-cli:preview