# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release Image To Docker Hub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    name: Build a release container image and push to Docker Hub 
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      
      - name: Test environment variable for release version
        run: echo ${{ env.RELEASE_VERSION }}

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:docker"
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ansible-azure-cli:${{ env.RELEASE_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/ansible-azure-cli:latest